Add a few more test pages
matomo-org/test-examples pull request #5
Opened 2021-04-08 09:40 UTC by Findus23

I really like the idea of having one set of websites where every Matomo feature can be tested.

I added a few more examples:
- MediaAnalytics
- TagManager
- the opt-out form explained in the developer docs
- a simple opt-in
- using Klaro consent manager (it seems to be the most popular one, is FOSS and supports Matomo explicitly)

2021-04-08 20:29 UTC, tsteur requested changes
Great @Findus23 very valuable 👍  left just a few minor comments

2021-04-08 20:29 UTC, tsteur commented on tagmanager/basic.php
> +        g.src = 'https://dev.matomo/js/container_<?php echo $matomoTagManagerContainer;?>.js'
@Findus23 it uses the hard coded domain here

2021-04-08 20:29 UTC, tsteur commented on config/config.example.php
> +$matomoTagManagerContainer = "ZNBuKNcy";
could maybe add this to the documentation in https://github.com/matomo-org/test-examples/blob/main/README.md#configuration ?

Add the beginning of the file could actually add a comment like below?

```php
// WHEN ADDING NEW VARIABLES PLEASE DOCUMENT THEM IN THE README
```

2021-04-08 20:29 UTC, tsteur commented on tagmanager/basic.php
> +<a href="?mtmPreviewMode=<?php echo $matomoTagManagerContainer;?>">Preview Mode</a>
could maybe add in brackets like `Preview Mode</a> (requires preview mode to be activated in Matomo)`?

2021-05-12 02:55 UTC, diosmosis commented
Merging this. If there are further changes that need to be made, they can always be done in another PR.

2021-05-12 02:55 UTC, merged